version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flask_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: flask_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://usuario:password@db:5432/flask_db
    ports:
      - "5000:5000"

volumes:
  postgres_data:
